### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by luna9806** [WeihongPan/Labelme2Culane#1]
我把annotations、gt_data、json、label、list、test_image、train_image、val_image都清空了，然后gt_data存放我的原图，json存放对原图标注生成的.json文件，名称和原图对应。关于路径设置config.yaml只改了dataset: C:\Users\18125\Desktop\Labelme2Culane-maingt_data其余的我都没变动，运行的时候出错了如下。

运行json_to_dataset.py报错如下：
`C:\Users\18125\Anaconda3\envs\labelme\python.exe C:/Users/18125/Desktop/Labelme2Culane-main/json_to_dataset.py
[WARNING] json_to_dataset:main:16 - This script is aimed to demonstrate how to convert the JSON file to a single image dataset.
[WARNING] json_to_dataset:main:20 - It won't handle multiple JSON files to generate a real-use dataset.
usage: json_to_dataset.py [-h] [-o OUT] json_file
json_to_dataset.py: error: the following arguments are required: json_file

进程已结束，退出代码为 2`

运行Labelme2Culane报错：
`C:\Users\18125\Anaconda3\envs\labelme\python.exe C:/Users/18125/Desktop/Labelme2Culane-main/Labelme2Culane.py
C:/Users/18125/Desktop/Labelme2Culane-main/Labelme2Culane.py:94: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(open('config.yaml').read())
Traceback (most recent call last):
  File "C:/Users/18125/Desktop/Labelme2Culane-main/Labelme2Culane.py", line 123, in <module>
    assert osp.exists(dataset)
AssertionError
------------------confirm paths---------------------------
image path: gt_data
json files: json
annotation files: annotations

进程已结束，退出代码为 1
`
希望得到您的回答，万分感谢。

**Comment by WeihongPan** [comment]
是我的readme文档手误了，配置好config文件直接运行Labelme2Culane.py就可以。你报的yaml错误应该是版本太高的缘故，网上也有相应的解决方法，可以去搜一下

**Comment by WeihongPan** [comment]
> 我把annotations、gt_data、json、label、list、test_image、train_image、val_image都清空了，然后gt_data存放我的原图，json存放对原图标注生成的.json文件，名称和原图对应。关于路径设置config.yaml只改了dataset: C:\Users\18125\Desktop\Labelme2Culane-maingt_data其余的我都没变动，运行的时候出错了如下。
> 
> 运行json_to_dataset.py报错如下：
> `C:\Users\18125\Anaconda3\envs\labelme\python.exe C:/Users/18125/Desktop/Labelme2Culane-main/json_to_dataset.py
> [WARNING] json_to_dataset:main:16 - This script is aimed to demonstrate how to convert the JSON file to a single image dataset.
> [WARNING] json_to_dataset:main:20 - It won't handle multiple JSON files to generate a real-use dataset.
> usage: json_to_dataset.py [-h] [-o OUT] json_file
> json_to_dataset.py: error: the following arguments are required: json_file
> 
> 进程已结束，退出代码为 2`
> 
> 运行Labelme2Culane报错：
> `C:\Users\18125\Anaconda3\envs\labelme\python.exe C:/Users/18125/Desktop/Labelme2Culane-main/Labelme2Culane.py
> C:/Users/18125/Desktop/Labelme2Culane-main/Labelme2Culane.py:94: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
> config = yaml.load(open('config.yaml').read())
> Traceback (most recent call last):
> File "C:/Users/18125/Desktop/Labelme2Culane-main/Labelme2Culane.py", line 123, in
> assert osp.exists(dataset)
> AssertionError
> ------------------confirm paths---------------------------
> image path: gt_data
> json files: json
> annotation files: annotations
> 
> 进程已结束，退出代码为 1
> `
> 希望得到您的回答，万分感谢。

是我的readme文档手误了，配置好config文件直接运行Labelme2Culane.py就可以。你报的yaml错误应该是版本太高的缘故，网上也有相应的解决方法，可以去搜一下

**Comment by luna9806** [comment]
已解决，修改了94行为
config = yaml.load(open('config.yaml', 'r', encoding='UTF-8').read())
修改路径，把中文路径修改掉，然后就行了，非常感谢

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月18日(周五) 中午11:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [WeihongPan/Labelme2Culane] 运行错误 (#1)




  
我把annotations、gt_data、json、label、list、test_image、train_image、val_image都清空了，然后gt_data存放我的原图，json存放对原图标注生成的.json文件，名称和原图对应。关于路径设置config.yaml只改了dataset: C:\Users\18125\Desktop\Labelme2Culane-maingt_data其余的我都没变动，运行的时候出错了如下。
 
运行json_to_dataset.py报错如下：
 `C:\Users\18125\Anaconda3\envs\labelme\python.exe C:/Users/18125/Desktop/Labelme2Culane-main/json_to_dataset.py
 [WARNING] json_to_dataset:main:16 - This script is aimed to demonstrate how to convert the JSON file to a single image dataset.
 [WARNING] json_to_dataset:main:20 - It won't handle multiple JSON files to generate a real-use dataset.
 usage: json_to_dataset.py [-h] [-o OUT] json_file
 json_to_dataset.py: error: the following arguments are required: json_file
 
进程已结束，退出代码为 2`
 
运行Labelme2Culane报错：
 `C:\Users\18125\Anaconda3\envs\labelme\python.exe C:/Users/18125/Desktop/Labelme2Culane-main/Labelme2Culane.py
 C:/Users/18125/Desktop/Labelme2Culane-main/Labelme2Culane.py:94: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
 config = yaml.load(open('config.yaml').read())
 Traceback (most recent call last):
 File "C:/Users/18125/Desktop/Labelme2Culane-main/Labelme2Culane.py", line 123, in
 assert osp.exists(dataset)
 AssertionError
 ------------------confirm paths---------------------------
 image path: gt_data
 json files: json
 annotation files: annotations
 
进程已结束，退出代码为 1
 `
 希望得到您的回答，万分感谢。
  
是我的readme文档手误了，配置好config文件直接运行Labelme2Culane.py就可以。你报的yaml错误应该是版本太高的缘故，网上也有相应的解决方法，可以去搜一下
